version: '3'
services:
  api:
    build: 
        context: backend
    ports:
        - 5000:5000
    volumes: ['./backend:/app']
  app:
    build:
      context: frontend
    ports:
      - 8080:80
    depends_on: 
      - api
   depends_on: 
       - db
 db:
   image: mongo:4.2.1
   ports:
       - 27017:27017
   volumes:
       - /db:/data/db
    