version: '3'
services:
  api:
    build: 
        context: backend
    ports:
        - 5000:5000
    volumes: ['./backend:/app']
    depends_on: 
        - db
  db:
    image: mongo:4.2.1
    ports:
        - 27017:27017
    volumes:
        - /db:/data/db
    